[wip] only considering 1 layer
SpecialeBajs/speciale-rapport pull request #18
Opened 2021-03-04 12:01 UTC by MathiasLybech

2021-03-29 10:28 UTC, Fatdet submitted a review, later dismissed

2021-04-09 13:46 UTC, jenspetur94 requested changes

2021-04-09 13:46 UTC, jenspetur94 commented on article/Experiment/experiment.tex
> +\textbf{RQ2}: How does LightGCN perform the final embedding is a certain convolution layer? \\
```suggestion
\textbf{RQ2}: How does LightGCN perform when only one convolution layer is used for the final embedding ? \\
```

2021-04-13 07:44 UTC, jenspetur94 approved these changes

2021-04-13 07:44 UTC, Fatdet approved these changes

2021-04-13 07:45 UTC, merged