skal huske at pushe mine ting lol
SpecialeBajs/speciale-rapport pull request #28
Opened 2021-04-27 11:06 UTC by Fatdet

2021-04-30 07:43 UTC, MathiasLybech requested changes

2021-04-30 07:43 UTC, MathiasLybech commented on article/Method/alpha-k-layer-combination.tex
> +    \caption{Algorithm for layer effect based on performance}
```suggestion
    \caption{Algorithm for the aggressive layer effect based on performance}
```

2021-05-11 09:35 UTC, jenspetur94 requested changes

2021-05-11 09:35 UTC, jenspetur94 commented on article/Method/alpha-k-layer-combination.tex
> +The algorithms looks at the performance of each individual layers and then based on how many percent's worse they perform compared to the best layer they will get a penalty in their effect and the ot
```suggestion
The algorithm looks at the performance of each individual layer and then based on how much worse they perform compared to the best layer they will get a penalty in their effect and the other layers will get an increase.
```

2021-05-11 09:35 UTC, jenspetur94 commented on article/Method/alpha-k-layer-combination.tex
> +Two algorithms have been created where one has a more aggressive approach, that can completely remove certain layers, and a more balanced approach, where each layer will be ensured influence.
```suggestion
Two algorithms have been created where one has a more aggressive approach, that can completely remove certain layers, and the other one has a more balanced approach, where each layer will be ensured influence.
```

2021-05-11 09:35 UTC, jenspetur94 commented on article/Method/alpha-k-layer-combination.tex
> +An example of the aggressive algorithm can be seen on \autoref{fig:fredsplitAgg} and and the balanced algorithm on \autoref{fig:fredsplitBal}.
```suggestion
An example of the aggressive algorithm can be seen on \autoref{fig:fredsplitAgg} and an example of the balanced algorithm can be seen on \autoref{fig:fredsplitBal}.
```

2021-05-11 09:35 UTC, jenspetur94 commented on article/Method/alpha-k-layer-combination.tex
> +Given four layers on \autoref{fig:fredsplitAgg} each layer will have 25\% effect on the final embedding at the start.
```suggestion
Given four layers on \autoref{fig:fredsplitAgg} each layer will have 25\% effect on the final embedding initially.
```

2021-05-11 09:35 UTC, jenspetur94 commented on article/Method/alpha-k-layer-combination.tex
>  Meanwhile, the 15 is split evenly among the other 3 layers who now have an effect of 30\%.
```suggestion
Meanwhile, the 15 is split evenly among the 3 other layers who now have an effect of 30\%.
```

2021-05-11 09:35 UTC, jenspetur94 commented on article/Method/alpha-k-layer-combination.tex
> +The algorithm is given a list of how much worse each layer performed in percentage compared to the best performing layer in the same list.
```suggestion
The algorithm is given a list of how much worse each layer performed in percentages compared to the best performing layer in the same list.
```

2021-05-13 10:39 UTC, MathiasLybech approved these changes

2021-05-13 10:40 UTC, jenspetur94 approved these changes

2021-05-13 10:40 UTC, merged