[wip] one weight added
SpecialeBajs/speciale-rapport pull request #31
Opened 2021-05-10 08:02 UTC by MathiasLybech

2021-05-18 12:09 UTC, Fatdet requested changes

2021-05-18 12:09 UTC, Fatdet commented on Appendix/lightgcn-1-weight.tex
> +Our intuition behind adding one weight would be that this could learn the layer combination, as there are weights for each layers.
kalde det noget andet en bare weight? det er vel en weight matrix/vector

2021-05-19 10:55 UTC, jenspetur94 requested changes

2021-05-19 10:55 UTC, jenspetur94 commented on Appendix/lightgcn-1-weight.tex
> +The core difference between NGCF and LightGCN is that LightGCN does not utilize weights and an activation function \cite{lightgcn,NGCF_2019}.
```suggestion
The core difference between NGCF and LightGCN is that LightGCN does not utilize learnable weight matrices and does not utlize an activation function \cite{lightgcn,NGCF_2019}.
```

2021-05-19 10:55 UTC, jenspetur94 commented on Appendix/lightgcn-1-weight.tex
> +Our intuition behind adding weights would be that this could learn the layer combination required, as there are weight matrices for each layers.
```suggestion
Our intuition behind adding a learnable weight matrix would be that we could learn how to perform the optimal layer combination, as there are learnable weights for each layers.
```

2021-05-19 11:22 UTC, merged