appendix rettelser
SpecialeBajs/speciale-rapport pull request #47
Opened 2021-05-28 07:47 UTC by MathiasLybech

2021-05-28 14:41 UTC, Fatdet requested changes

2021-05-28 14:41 UTC, Fatdet commented on Appendix/degree-experiment.tex
> +This was conducted to gain and understanding of how well the different node degrees performs with the LightGCN layer combination.
```suggestion
This was conducted to gain an understanding of how well the different node degrees performs with the LightGCN layer combination.
```

2021-05-28 14:41 UTC, Fatdet commented on Appendix/remove-0-embedding.tex
> +\autoref{fig:recall-yelp2020-alpha-k} shows the recall results LightGCN and LightGCN-Ak1 on Yelp2020.
```suggestion
\autoref{fig:recall-yelp2020-alpha-k} shows the recall results for LightGCN and LightGCN-Ak1 on Yelp2020.
```

2021-06-01 08:47 UTC, jenspetur94 requested changes

2021-06-01 08:47 UTC, jenspetur94 commented on Appendix/degree-experiment.tex
> +This section contains the recall results conducted in \autoref{subsec:degree-experiment}.
```suggestion
This section contains the recall performance from the experiments conducted in \autoref{subsec:degree-experiment}.
```

2021-06-01 08:47 UTC, jenspetur94 commented on Appendix/degree-experiment.tex
> +\section{Average LightGCN results}\label{app:average-lightgcn-results}
hvorfor hedder det her Average LightGCN ?

2021-06-01 08:47 UTC, jenspetur94 commented on Appendix/degree-experiment.tex
> +This section shows the performance of LightGCN on Yelp2020, Amazon-Book and Amazon-Cell-Sport with one to five convolutions and node degree evaluated.
```suggestion
This section shows the performance of LightGCN on Yelp2020, Amazon-Book and Amazon-Cell-Sport with one to five convolutions.
The performance of different node degrees is also evaluated.
```

2021-06-01 08:47 UTC, jenspetur94 commented on Appendix/degree-experiment.tex
> +This was conducted to gain an understanding of how well the different node degrees performs with the LightGCN layer combination.
```suggestion
This was conducted to gain an understanding of how well the different node degrees perform in LightGCN with its standard layer combination.
```

2021-06-01 08:47 UTC, jenspetur94 commented on Appendix/gcf-recall-ablation-study.tex
> +Additionally some figures have been split up to only include the methods utilizing summation or concatenation to more easily compare the methods.
```suggestion
Additionally, some figures have been split up to only include the methods utilizing summation or concatenation to more easily compare the methods.
```

2021-06-01 08:47 UTC, jenspetur94 commented on Appendix/remove-0-embedding.tex
> +This section contains the other results of removing $\alpha_k$ and removing the 0th embedding.
referer til experimenter

2021-06-01 09:08 UTC, Fatdet approved these changes

2021-06-01 09:12 UTC, jenspetur94 approved these changes

2021-06-01 09:12 UTC, merged