abstract suggested
SpecialeBajs/speciale-rapport pull request #49
Opened 2021-05-28 08:38 UTC by MathiasLybech

2021-05-28 14:43 UTC, Fatdet commented on article/Abstract.tex
> +These are used as alternative layer combination methods for graph convolutional networks instead of using means.
Er enig i at der burde stå means men lgcn kalder det weighted summation og det kalder vi den også i resten af rapporten så måske vi skulle ændre det til det?

2021-06-01 09:34 UTC, jenspetur94 approved these changes

2021-06-01 09:34 UTC, jenspetur94 commented on article/Abstract.tex
> +We also conduct an ablation study for GCF to understand why it outperformed LightGCN on their datasets.
```suggestion
An ablation study for GCF is also conducted to understand why it outperformed LightGCN on their datasets.
```

2021-06-01 09:34 UTC, jenspetur94 commented on article/Abstract.tex
> +Both ALC and BLC showed to outperform GCF.
```suggestion
ALC and BLC both outperformed GCF.
```

2021-06-01 09:34 UTC, jenspetur94 commented on article/Abstract.tex
> +Additionally we experimented with some edge cases, where only one embedding layer were used and only removing the 0th embedding layer.
```suggestion
Additionally, we experimented with some edge cases, where only one embedding layer was used or where the 0th embedding is removed.
```

2021-06-01 09:35 UTC, jenspetur94 requested changes
fix mine ting

2021-06-01 10:12 UTC, Fatdet approved these changes

2021-06-01 10:13 UTC, merged