described embeddings
SpecialeBajs/speciale-rapport pull request #5
Opened 2021-02-08 11:19 UTC by MathiasLybech

2021-02-08 13:06 UTC, Fatdet requested changes

2021-02-08 20:12 UTC, Fatdet approved these changes

2021-02-09 08:52 UTC, Moesgaarda commented
Det er sgu godt arbejde

2021-02-09 08:53 UTC, Fatdet commented
> Det er sgu godt arbejde

Tak fae han er bare så dygtig ham Mathias

2021-02-09 08:56 UTC, Moesgaarda commented on article/Method/embeddings.tex
> +The original use for GCN was proposed on node classification where each node has rich attributes, but for collaborative filtering the nodes only contains node IDs \cite{lightgcn,kipf2017semisupervise
```suggestion
The original use for GCN was proposed on node classification where each node has rich attributes, but for collaborative filtering, the nodes only contain node IDs \cite{lightgcn,kipf2017semisupervised,NGCF_2019}.
```

useriøst

2021-02-09 08:56 UTC, Moesgaarda commented on article/Method/embeddings.tex
> +This is something that LightGCN took advantage of and simplified NGCF by removing the non linear activation function and the feature transformation, which showed promising results in their experiment
```suggestion
This is something that LightGCN took advantage of and simplified NGCF by removing the nonlinear activation function and the feature transformation, which showed promising results in their experiments.
```

2021-02-09 09:20 UTC, jenspetur94 requested changes

2021-02-09 09:20 UTC, jenspetur94 commented on article/Method/embeddings.tex
> +Later Meng Liu et. al then created a method called BiTGCF which utilized GCN and transfer learning between two different datasets \cite{BiTGCF}.
```suggestion
Later Meng Liu et. al then created a method called BiTGCF which utilized GCN and transfer learning between two domains \cite{BiTGCF}.
```

2021-02-09 09:20 UTC, jenspetur94 commented on article/Method/embeddings.tex
> +The embedding propagation for NGCF is defined as,
```suggestion
The embedding propagation in NGCF is defined as,
```

2021-02-09 09:20 UTC, jenspetur94 commented on article/Method/embeddings.tex
> +where LeakyReLU is the nonlinear activation function and $\mathbf{m}^{(k)}_{u \leftarrow i}$ is the message construction from users u to item i, and $\mathbf{m}^{(k)}_{u \leftarrow u}$ is the self co
```suggestion
where LeakyReLU is the nonlinear activation function, $\mathbf{m}^{(k)}_{u \leftarrow i}$ is the message construction from users u to item i, and $\mathbf{m}^{(k)}_{u \leftarrow u}$ is the self connection.
```

2021-02-09 09:20 UTC, jenspetur94 commented on article/Method/embeddings.tex
> +The purpose of the inner product is that the more the user and item nodes has in common the greater the value will be passed to the center node \cite{BiTGCF}.
```suggestion
The purpose of the inner product is that the more the user and item nodes have in common the greater the value will be passed to the center node \cite{BiTGCF}.
```

2021-02-09 11:17 UTC, Fatdet approved these changes

2021-02-09 11:28 UTC, jenspetur94 approved these changes

2021-02-09 11:32 UTC, merged